### ISSUE TITLE
Fehler beim Installieren in Contao 4.9.1 

### ISSUE THREAD

**Issue by wschern** [FBHoMe/taxonomee-bundle#1]
Folgender Fehler wird angezeigt beim Installieren über den Contao-Manager in Contao 4.9.1:

> In tl_taxonomee.php line 90:
>
>Attempted to load class "DcaHelper" from namespace "Home\PearlsBundle\Resources\contao\Helper\Dca".
>
>Did you forget a "use" statement for another namespace ?

**Comment by theDyingMountain** [comment]
Hatte den gleichen Fehler. Zuerst muss home/pearls-bundle installiert werden. Dann funktioniert es.
